### ISSUE TITLE
视频解析不了

### ISSUE THREAD

**Issue by heartbeat986** [YSMull/fenbi-helper#3]
{ code: -2, msg: '无当前资源权限', total: 0, datas: [] }

**Comment by payerus** [comment]
这个咋用的啊？

**Comment by heartbeat986** [comment]
> 这个咋用的啊？

进入文件夹，敲`node app.js`

**Comment by payerus** [comment]
谢谢

**Comment by payerus** [comment]
没啥反应啊，也没有输出  也没有跳转  已经安装了node环境和相关的模块了，没报错，也没反应？
![image](https://user-images.githubusercontent.com/44284221/100179541-3ed49200-2f11-11eb-9d2b-d20ef5e89f12.png)

**Comment by payerus** [comment]
弄好了，原来这个程序监听了3000端口，对于没学过node的人来说有点不知所措，谢谢了

**Comment by UltramarineSky** [comment]
用3000的登录后出现了这个
```
PS D:\Program Files\fenbi-helper-master\src> node app.js
(node:11344) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

  TypeError: Cannot read property 'filter' of undefined
      at getCategories (D:\Program Files\fenbi-helper-master\src\service\exercisesResult.js:32:51)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.exports.getExerciseHistory (D:\Program Files\fenbi-helper-master\src\service\exercisesResult.js:322:22)
      at async D:\Program Files\fenbi-helper-master\src\app.js:100:37
      at async serve (D:\Program Files\nodejs\node_global\node_modules\koa-static\index.js:53:9)
```
请问这种要怎么解决啊，网上搜了下有些没弄懂
